

# 端口
server:
  port: 7003
  #eureka客户端配置
eureka:
  instance:
    hostname: localhost
    statuspageUrl: http://localhost:7003/index
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: pmit-project-prjmanager




